[[constraint]]
  name = "github.com/brettbuddin/musictheory"
  version = "0.0.14"

[[constraint]]
  name = "github.com/gordonklaus/portaudio"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.0.0"

[[constraint]]
  name = "github.com/rakyll/portmidi"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  name = "github.com/c-bata/go-prompt"
  version = "0.2.2"
